version: '3.8'

services:

  database:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=PRUEBA_FUND_DAT_RELAC

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mired


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: jonhdoe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StrongPassword
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mired

volumes:
  postgres_data:
  pgadmin_data:


networks:
  mired:
    driver: bridge